// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDeEupTd2IrWdnBlBv1anZP2nxNJ8zky4U',
    appId: '1:501841860383:web:2e8d26fbf5bc8de5b8022a',
    messagingSenderId: '501841860383',
    projectId: 'miabe-pharmacie',
    authDomain: 'miabe-pharmacie.firebaseapp.com',
    storageBucket: 'miabe-pharmacie.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFAaqe7HyKOMWI-lo5eSKFkpVn1Mrr5qA',
    appId: '1:501841860383:android:d69601d7391b5603b8022a',
    messagingSenderId: '501841860383',
    projectId: 'miabe-pharmacie',
    storageBucket: 'miabe-pharmacie.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBRG_EGO9CibTn3xucwm7vOTUcwvmOnicA',
    appId: '1:501841860383:ios:12c16d51107fcfdbb8022a',
    messagingSenderId: '501841860383',
    projectId: 'miabe-pharmacie',
    storageBucket: 'miabe-pharmacie.firebasestorage.app',
    iosClientId: '501841860383-j5iromfeu2hek10v2lodl5phjef9vot0.apps.googleusercontent.com',
    iosBundleId: 'com.example.miabePharmacie',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBRG_EGO9CibTn3xucwm7vOTUcwvmOnicA',
    appId: '1:501841860383:ios:12c16d51107fcfdbb8022a',
    messagingSenderId: '501841860383',
    projectId: 'miabe-pharmacie',
    storageBucket: 'miabe-pharmacie.firebasestorage.app',
    iosClientId: '501841860383-j5iromfeu2hek10v2lodl5phjef9vot0.apps.googleusercontent.com',
    iosBundleId: 'com.example.miabePharmacie',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDeEupTd2IrWdnBlBv1anZP2nxNJ8zky4U',
    appId: '1:501841860383:web:beff0f0cc6e99814b8022a',
    messagingSenderId: '501841860383',
    projectId: 'miabe-pharmacie',
    authDomain: 'miabe-pharmacie.firebaseapp.com',
    storageBucket: 'miabe-pharmacie.firebasestorage.app',
  );
}
